### ISSUE TITLE
Spinning Wheel when selecting "Toggle Full Screen Mode" Deus Ex [GMDX v10]

### ISSUE THREAD

**Issue by Euther** [cdown/chrisdown.name#29]
Good day,
Deus Ex [GMDX v10]

Trying to save the initial load of the game in Bordered Windows Mode. All I get is a spinning wheel when selecting "Toggle Full Screen Mode". It is acting like it is NOT saving to the GMDXv10.ini file. If I set the parameter BorderlessFullscreenWindow=False when the game loads it is still in Fullscreen. My resolution is also set at: 
WindowedViewportX=1920
WindowedViewportY=1080 

Any advise ?

Thank you,
E

**Comment by cdown** [comment]
Sorry -- I think you've got the wrong place, no idea why you're filing this here.
